jobs:

- job: 'macOS'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python38:
        python.version: '3.8'
        pyver: 'py38'
      Python37:
        python.version: '3.7'
        pyver: 'py37'
      Python36:
        python.version: '3.6'
        pyver: 'py36'
    maxParallel: 2
  steps:
  - script: |
      echo "##vso[task.prependpath]$HOME/.cargo/bin"
  - template: .ci/azure-steps.yml

- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python38:
        python.version: '3.8'
        pyver: 'py38'
      Python37:
        python.version: '3.7'
        pyver: 'py37'
      Python36:
        python.version: '3.6'
        pyver: 'py36'
    maxParallel: 2
  steps:
  - script: |
      echo ##vso[task.prependpath]%USERPROFILE%\.cargo\bin
  - template: .ci/azure-steps.yml
