dist: xenial
language: python
python:
- 3.6
- 3.7
cache:
  pip: true
  cargo: true
install:
- pip install --upgrade pip poetry
- curl https://sh.rustup.rs -sSf | sh -s -- -y -v --default-toolchain nightly
- source "$HOME"/.cargo/env
- cargo install maturin
- poetry install --no-dev
before_script:
- rustc --version
script:
- poetry run maturin develop
deploy:
  provider: script
  script: ".ci/deploy_to_pypi.sh"
  on:
    tags: true
    repo: robertodr/rustafarian
    python: 3.6
  password:
    secure: eAcS/VzTCVkIFuLhDok0cfJlPtVKRE+ktj45jvcOir3c6xYkO+BKh996gtycKFkT8oHa4k1ZRxYLQR9pm71gvlXQA7BKa3A8Y/VT4q7ZBqG2MMMEn5dgrGSr5svU5MzpyPa++h0sKMpj48atB/OraDbRuhjvnX7NxMqLPmHu5q0B7y+XezjnSajEVKZIFzDP8pf57TOZoRKb8OFgn9+EyvrB4RP57xwtjBFRixcSuJGihhTJxwzAD6yM+iEbEy3h4AUpEkOx9kNmgWpCO4TyZdvkZkLp/lrAvHBwwUCPIZ0wxM0IVEvjan+hz1IFxybVMQkRs/GHVAhe4rDuN31IykXZe1gzOmG+2hPNrle8v7ThM1f+EMigYH0OvQMp2Fxr3SyTKRW5vwpO+6tNCb4m84gmaTNhC2b6jkgkkSHB2YHltPpGf0aNmdWFIGCdCVmAi1ngv+2afiTCqH45HGArmAUSyHXJPG7cNUVvad5+PDoNfZHoaNKbTUASe6o/DiwaVh+NQr9Of97GFlQ5+lrmKYyuDSDhRCX2XIoHhBnzCrKFbkfOX11pcoEbVc+/Vz26XYuOkS19q4tmLylyGGbTeWLckcx0qYRHmQxTqHTgoBN7H+Z84vXLJr1Z5y9GT1tgiTjVtlvpYu/D8sYoRm4iDiZP9rUHdd/e73hZzI+0eQQ=
