dist: xenial

language: python

python:
  - 3.6
  - 3.7
  - 3.8-dev

allow_failures:
  - 3.8-dev

cache:
  pip: true
  cargo: true

before_cache:
  - rm -rfv target/debug/incremental/{rustafarian,build_script_build,common}-*
  - rm -rfv target/debug/.fingerprint/rustafarian-*
  - rm -rfv target/debug/build/rustafarian-*
  - rm -rfv target/debug/deps/librustafarian-*
  - rm -rfv target/debug/deps/rustafarian-*
  - rm -rfv target/debug/{rustafarian,librustafarian}.d
  - cargo clean -p rustafarian

env:
  global:
    - TRAVIS_RUST_VERSION=nightly
    - RUST_BACKTRACE=1
    - secure: HD6R3/zEiR0r0ZI451QCM+UM/uNEbNFB2xq0HppzK0OzwaRjSoHbFOG/en49kFyQRE+Y7EdZdaiWptIq19xC/gGcxgMtCKDAhhudyVK4vg9VTyga78CHrCJJs+oqw6/PRrQ9YuxuF92wEknBPZPpaswZ1nXIfG+pwnAJ9eIqk8JAfiOhsfyQf2Ppe75dvLQloHOzryFws+s375N33nAh55GdaNGjvknTsu54yOtZWql1mhmPCI1jDZPWjFdbOCsY8AhCP2hkt+gCa2+1/XsVNwGKdGCyOCr3TvWA11Sz+fZSsoOi9REgpTcDKkxjLjsiR7GMlwSqEQyvwo+Vb+MNLiuV8u/+V3Z0/ICGENokHUhmP5bluwlreJ6DTiq4FwSAnu8nOUbVgm7PLNcmV5lMxGHGcRvnSnzdnLx8+ozoE5nH+hpKk2hdHrFEhJBtxlbREn74V91yaQotqtM1BiMedGuBxqdmGdnsDLwpKWBwp2fkQac/cgBOo/oVCgP05Do6AdvK1K1/B4t+sDUOwA9ZooSVVz7v0CamMI8homQ5ZAhAoYZ6xiFROwK+RfDI5Ijstpj99GT/bOEBL0JKUyvCb8SFpD+30CCorN5wWDk0WEMqc5ys2IVEYv4JTJsVyF7ZU9W1z3ejHrZ4PsfTTvU0xdm3+/JCnbh70s3gMJpmqzM=

install:
  - pip install --upgrade pip poetry
  - curl https://sh.rustup.rs -sSf | sh -s -- -y -v --default-toolchain=$TRAVIS_RUST_VERSION
  - source "$HOME"/.cargo/env
  - poetry install

before_script:
  - rustc --version

script:
  - poetry run maturin develop

deploy:
  provider: script
  script: ".ci/deploy_to_pypi.sh"
  on:
    tags: true
    repo: robertodr/rustafarian
    python: 3.6
