dist: xenial

language: python

python:
  - 3.6
  - 3.7

# See https://gist.github.com/jkcclemens/000456ca646bd502cac0dbddcb8fa307
cache:
  pip: true
  cargo: true
before_cache:
  - rm -rfv target/debug/incremental/{rustafarian,build_script_build,common}-*
  - rm -rfv target/debug/.fingerprint/rustafarian-*
  - rm -rfv target/debug/build/rustafarian-*
  - rm -rfv target/debug/deps/librustafarian-*
  - rm -rfv target/debug/deps/rustafarian-*
  - rm -rfv target/debug/{rustafarian,librustafarian}.d
  - cargo clean -p rustafarian

install:
  - pip install --upgrade pip poetry
  - curl https://sh.rustup.rs -sSf | sh -s -- -y -v --default-toolchain nightly
  - source "$HOME"/.cargo/env
  - cargo install maturin
  - poetry install --no-dev

before_script:
  - rustc --version

script:
  - poetry run maturin develop

env:
  global:
    secure: Z53BFQvT8J8t65hbKG//k+WvfI0K35yhKVu8gaR31JonFLW8biyMFqtPcmCJDbNt+qH3qZQr2ieRd2pYc27Reau5ckCPdd0jNvXj6ogY4+PPbV5pfHaWLVeOizAPxohv4OabppmP01sf8u0dFOYVcrEPkr4rtV3r+ldt9rZxRlOPfy6f309ulplJ9+UX0nNhMq9EJmHR0wtADznYyIdK1wI5qItGo7YqKeauOUe+/YiyYAh9UhxUAGVlhNfzHo3lZfpzTDV4/HnWTQq2qSyZI/Jb0FAOyqIgp10YExoww2Py0MFjcBbjMGuEvDsXZp1LL1jPbjFIkmhZHKK65ZNAd6lbpn3+ENSPctQAglArPLwwPO5e/uGsTdLTMIzCw8sfReqPLo4xTqwDW0LkVpCZSZZKOdISALodDA1dZKlz0z2M6aXLGTYSIhtbm2BO23UU7bV9W+kWt6xEPxYPuvPOIOoK20Kj8fmx6JbuCv5xH9x9tAH67Y+wrwVcJtLvgVA6iJof5vo0siNoO7bySTvHus05qQtZFpI3adeElUPnuqu/mxz9cnSmDirIaMuuxllJukLOIO0jwganKOefYalXCMTEdON0tGNCosvkcObNvtOSGr7XI/EQ3Dfwx4d/dwIQGj+OUIHebCNkEiK+MhnhMEePCowB5y0V/m1zNW0pEyw=

deploy:
  provider: script
  script: ".ci/deploy_to_pypi.sh"
  on:
    tags: true
    repo: robertodr/rustafarian
    python: 3.6
