dist: xenial
language: python
python:
- 3.7
- 3.6
- 3.5
cache:
  pip: true
  directories:
  - "$HOME/.cargo"
install:
- pip install --upgrade pip pipenv
- curl https://sh.rustup.rs -sSf | sh -s -- -y -v --default-toolchain nightly-2019-01-15
- source "$HOME"/.cargo/env
- pipenv install --dev
before_script:
- rustc --version
script:
- pipenv run pyo3-pack develop
after_success:
- >
  pipenv run pyo3-pack publish
             --username robertodr
             --password EBstcfz0D3Jq1JqvRh4b4gGwZLEEmP15S+zLiG7GIUHn2FAxx6IUw3AAGY3HtxKTL2EPxpzEluGgbvytuJiBKyvN9w4rYf/+AJCusDuK1Yn63WmLo152GchxA9Y6tiE3L7Ri0n0F7MrUPokOUEwW4HiJSn6RTZav/n8lYU3/Q9i0TPKIg+yLNyT9jUqCqhtnwGHWK2nrk6AH+JCr5pRapteSvLP5JnAQSNFoP1yl9drRW5faGEyv13kfeBx5RBS93oww3n2kWFuE/4asRSAxJPojuRzf27ihgYR20vTenNGJozsItM4xSZeyhO3ygTYB7dr5s8kRfc9zzhdqA4gxbfChQ30VqDj1doINajANesa7hSv2ew3MpbKcmF0oCrLat5RSW25It87k4VS364WyJ3/c7L0y25Mu4mKZUWCdCZ2TGRod6ppDDL26nHqqEJQIQkeH6EeL/FvaZ5KiFdIOYfolixnr7RVVVX+EZNTcSm1SLVv0zLyP0UtaoB32/A9Js0mK5i7JSXFYLd71nRwca6uFsTet8BQfHORKyMuEkckb+PvlYEuv7BMOJHcCrop9gkZuPVWHVaH3hq2mu0yWHWkiHsGdq0qU4ilhv765fxNhoP49b3/Fp4ImFa5yQl6EAfhA2kCXI3eu/e51eqQZMgYQjKRWdK8PosHe62Z6Xg8=
             --repository-url https://test.pypi.org/legacy/
