[package]
name = "rustafarian"
version = "0.1.0"
edition = "2019"
authors = ["Roberto Di Remigio <roberto.diremigio@gmail.com>"]

[lib]
name = "rustafarian"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.6.0-alpha.2"
features = ["extension-module"]
