[package]
name = "rustafarian"
version = "0.1.0"
edition = "2018"
authors = ["Roberto Di Remigio <roberto.diremigio@gmail.com>"]

[lib]
name = "rustafarian"
crate-type = ["rlib", "cdylib"]

[dependencies.pyo3]
version = "0.6.0-alpha.2"

[features]
default = ["pyo3/extension-module"]

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
