[package]
name = "rustafarian"
version = "0.3.6"
edition = "2018"
authors = ["Roberto Di Remigio <roberto.diremigio@gmail.com>"]

[package.metadata.maturin.scripts]
get_42 = "rustafarian:get_42"

[dependencies]
pyo3 = { version = "0.7.0", features = ["extension-module"]}
maturin = { version = "0.7.1" }

[lib]
name = "rustafarian"
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
