version: 2

jobs:
  build:
    docker:
      - image: konstin2/maturin:master

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
